// <auto-generated />
namespace GBHS_HospitalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addSuongtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addSuongtable));
        
        string IMigrationMetadata.Id
        {
            get { return "202107221631352_add-Suong-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
