// <auto-generated />
namespace GBHS_HospitalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserIDFKPatient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserIDFKPatient));
        
        string IMigrationMetadata.Id
        {
            get { return "202108061635277_UserID-FK-Patient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
