// <auto-generated />
namespace GBHS_HospitalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SpecialistBookingRelationshipAppointment_Feature : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SpecialistBookingRelationshipAppointment_Feature));
        
        string IMigrationMetadata.Id
        {
            get { return "202107221926173_Specialist-Booking-Relationship-Appointment_Feature"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
